### ISSUE TITLE
Include the official GitHub app

### ISSUE THREAD

**Issue by erikjung** [cloudfour/cloudfour-boxen#47]
I've pretty much ditched Tower as my Git GUI. I really liked it, but it was buggy with submodules. 

The GitHub app is nice. Less features, but still plenty. And free.

```sh
brew cask install github
```

**Comment by lyzadanger** [comment]
I was actually going to get this done today! But, alas, `github-desktop` is one of the `brewcask` packages that suffers from this problem: https://github.com/boxen/puppet-brewcask/issues/22

It's the same issue I ran into with `virtualbox` the other day, so I'm going to close this for now as not-reasonably-do-able with `boxen`.
