### ISSUE TITLE
Ruby/bundler errors on El Capitan

### ISSUE THREAD

**Issue by erikjung** [cloudfour/cloudfour-boxen#62]
- [ ] Ruby/Bundler versions getting messed up by OS X update
    ```
    rbenv: bundle: command not found

    The `bundle' command exists in these Ruby versions:
      2.0.0
      2.0.0-p353
      2.1.0
      2.1.2

    find: bin: No such file or directory
    Can't run Puppet, fetching dependencies with librarian failed.
    ```
    https://cloudfour.slack.com/archives/general-dev/p1445964791000002

**Comment by lyzadanger** [comment]
I'm going to rename this issue because it's specific to the ruby/bundler issue. Here is a (more permanent) workaround:

https://github.com/boxen/our-boxen/issues/794#issuecomment-159541053

**Comment by lyzadanger** [comment]
Unbelievably we haven't written down the workaround :).

It's something along the lines of:

```
cd /opt/boxen/repo
sudo gem install bundler
sudo bundle install
```

Yes, `sudo`, gross. I know.

**Comment by lyzadanger** [comment]
All team members are now on El Capitan so I am going to close this issue (we can still reference it if needed, later).
